### ISSUE TITLE
How to enable time integration in periodic forces test

### ISSUE THREAD

**Issue by hkayabilisim** [N-BodyShop/tests#3]
Hi Dr. Quinn,

I want to enable time integration in  [lambs_30K.param](https://github.com/N-BodyShop/tests/blob/master/forces/periodic/lambs_30K.param). Changing "nSteps = 0" to "nSteps = 10" didn't work. What other options should I add or modify to enable simplest possible time integration scheme allowed in ChaNGa? 

Huseyin

**Comment by trquinn** [comment]
The force test files are not meant for time integration for a number of reasons.  Perhaps the most significant reason is that the gravitational softenings are set to "0.0" to test pure 1/r^2 forces.  Using such softenings in a time integration will give very inaccurate results.
I recommend the periodic simulation in the `testcosmo` subdirectory of the ChaNGa source repository for an example cosmological time integration.

**Comment by hkayabilisim** [comment]
Thank you for the info.
